import smtplib
import subprocess
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# =========================
# CONFIGURAÇÕES
# =========================
EMAIL_REMETENTE = "inteligenciapricing@gmail.com"
SENHA_APP = "xjxc sqrw hihd toal"

DESTINATARIOS = [
    "fabio.furtado@greencarepharma.com.br",
    "sabrina.albertoni@greencarepharma.com.br",
    "gustavo.franceli@greencarepharma.com.br",
    "marcelo.ma@greencarepharma.com.br",
    "marcelo.macedo@greencarepharma.com.br",
    "marcelo.caetano@greencarepharma.com.br",
    "edmar.neix@greencarepharma.com.br",
    "filipe.lopes@greencarepharma.com.br",
    "flavio.brito@greencarepharma.com.br",
    "denil.rabelo@greencarepharma.com.br",
    "vagner.soares@greencarepharma.com.br",
    "felipe.santos@greencarepharma.com.br",
    "hamza.yaziji@greencarepharma.com.br",
    "martim.mattos@greencarepharma.com.br",
    "nelson@greenfield.global"
]

ASSUNTO_EMAIL = "GreenCare | Pricing Intelligence Report"


# =========================
# GERAR RELATÓRIO
# =========================
def gerar_relatorio_texto():
    resultado = subprocess.run(
        ["python", "scripts/analisador_precos.py"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace"
    )

    if resultado.returncode != 0:
        raise RuntimeError(
            "Erro ao gerar relatório\n"
            f"STDOUT:\n{resultado.stdout}\n\nSTDERR:\n{resultado.stderr}"
        )

    return resultado.stdout


def montar_html_relatorio(conteudo_texto: str) -> str:
    data_ref = datetime.now().strftime("%d/%m/%Y %H:%M")

    conteudo_html = (
        conteudo_texto
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    html = f"""
    <html>
        <body style="margin:0; padding:0; background-color:#f4f6f8; font-family:Arial, Helvetica, sans-serif; color:#1f2937;">
            <div style="max-width:980px; margin:30px auto; background:#ffffff; border:1px solid #e5e7eb; border-radius:12px; overflow:hidden;">
                
                <div style="background:#0f172a; padding:24px 32px;">
                    <div style="font-size:12px; letter-spacing:1px; color:#cbd5e1; text-transform:uppercase;">
                        GreenCare Pharma
                    </div>
                    <div style="margin-top:6px; font-size:28px; font-weight:700; color:#ffffff;">
                        Pricing Intelligence Report
                    </div>
                    <div style="margin-top:8px; font-size:14px; color:#cbd5e1;">
                        Competitive pricing monitoring | GreenCare vs Mantecorp
                    </div>
                </div>

                <div style="padding:24px 32px 12px 32px;">
                    <table style="width:100%; border-collapse:collapse;">
                        <tr>
                            <td style="font-size:13px; color:#6b7280; width:180px;">Reference date</td>
                            <td style="font-size:14px; color:#111827; font-weight:600;">{data_ref}</td>
                        </tr>
                        <tr>
                            <td style="font-size:13px; color:#6b7280; padding-top:10px;">Report scope</td>
                            <td style="font-size:14px; color:#111827; font-weight:600; padding-top:10px;">
                                Networks monitored and competitive pricing dispersion by SKU
                            </td>
                        </tr>
                    </table>
                </div>

                <div style="padding:12px 32px 32px 32px;">
                    <div style="font-size:15px; font-weight:700; color:#111827; margin-bottom:12px;">
                        Executive output
                    </div>

                    <div style="background:#0b1220; border-radius:10px; padding:20px; overflow:auto;">
                        <pre style="margin:0; white-space:pre-wrap; word-wrap:break-word; font-size:13px; line-height:1.55; color:#e5e7eb; font-family:Consolas, 'Courier New', monospace;">{conteudo_html}</pre>
                    </div>
                </div>

                <div style="border-top:1px solid #e5e7eb; padding:16px 32px; background:#fafafa; font-size:12px; color:#6b7280;">
                    Automated distribution generated by GreenCare Pricing Intelligence Engine
                </div>
            </div>
        </body>
    </html>
    """
    return html


# =========================
# ENVIAR EMAIL
# =========================
def enviar_email(conteudo_html: str):
    msg = MIMEMultipart("alternative")
    msg["From"] = EMAIL_REMETENTE
    msg["To"] = ", ".join(DESTINATARIOS)
    msg["Subject"] = ASSUNTO_EMAIL

    corpo_html = MIMEText(conteudo_html, "html", "utf-8")
    msg.attach(corpo_html)

    with smtplib.SMTP("smtp.gmail.com", 587, timeout=60) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(EMAIL_REMETENTE, SENHA_APP)
        server.sendmail(EMAIL_REMETENTE, DESTINATARIOS, msg.as_string())


# =========================
# EXECUÇÃO
# =========================
def run():
    print("Gerando relatório...")
    relatorio_texto = gerar_relatorio_texto()

    print("Montando email...")
    relatorio_html = montar_html_relatorio(relatorio_texto)

    print("Enviando email...")
    enviar_email(relatorio_html)

    print("Email enviado com sucesso!")


if __name__ == "__main__":
    run()
